version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: stocks-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stocksdb
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: stocks-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"